//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_Shipment_Client.ShippingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetailCenter", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RetailCenter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShippingService.ABC_ShippingServiceSoap")]
    public interface ABC_ShippingServiceSoap {
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRC", ReplyAction="*")]
        ABC_Shipment_Client.ShippingService.insertRCResponse insertRC(ABC_Shipment_Client.ShippingService.insertRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertRC", ReplyAction="*")]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertRCResponse> insertRCAsync(ABC_Shipment_Client.ShippingService.insertRCRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRC", ReplyAction="*")]
        ABC_Shipment_Client.ShippingService.updateRCResponse updateRC(ABC_Shipment_Client.ShippingService.updateRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRC", ReplyAction="*")]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.updateRCResponse> updateRCAsync(ABC_Shipment_Client.ShippingService.updateRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletetRC", ReplyAction="*")]
        bool deletetRC(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletetRC", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deletetRCAsync(int id);
        
        // CODEGEN: Generating message contract since element name searchRCResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchRC", ReplyAction="*")]
        ABC_Shipment_Client.ShippingService.searchRCResponse searchRC(ABC_Shipment_Client.ShippingService.searchRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchRC", ReplyAction="*")]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.searchRCResponse> searchRCAsync(ABC_Shipment_Client.ShippingService.searchRCRequest request);
        
        // CODEGEN: Generating message contract since element name ins from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertShipItem", ReplyAction="*")]
        ABC_Shipment_Client.ShippingService.insertShipItemResponse insertShipItem(ABC_Shipment_Client.ShippingService.insertShipItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertShipItem", ReplyAction="*")]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertShipItemResponse> insertShipItemAsync(ABC_Shipment_Client.ShippingService.insertShipItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteShipItem", ReplyAction="*")]
        bool deleteShipItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteShipItem", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteShipItemAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertRC", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.insertRCRequestBody Body;
        
        public insertRCRequest() {
        }
        
        public insertRCRequest(ABC_Shipment_Client.ShippingService.insertRCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertRCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        public insertRCRequestBody() {
        }
        
        public insertRCRequestBody(int id, string type, string address) {
            this.id = id;
            this.type = type;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertRCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertRCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.insertRCResponseBody Body;
        
        public insertRCResponse() {
        }
        
        public insertRCResponse(ABC_Shipment_Client.ShippingService.insertRCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertRCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertRCResult;
        
        public insertRCResponseBody() {
        }
        
        public insertRCResponseBody(bool insertRCResult) {
            this.insertRCResult = insertRCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRC", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.updateRCRequestBody Body;
        
        public updateRCRequest() {
        }
        
        public updateRCRequest(ABC_Shipment_Client.ShippingService.updateRCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        public updateRCRequestBody() {
        }
        
        public updateRCRequestBody(int id, string type, string address) {
            this.id = id;
            this.type = type;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.updateRCResponseBody Body;
        
        public updateRCResponse() {
        }
        
        public updateRCResponse(ABC_Shipment_Client.ShippingService.updateRCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool updateRCResult;
        
        public updateRCResponseBody() {
        }
        
        public updateRCResponseBody(bool updateRCResult) {
            this.updateRCResult = updateRCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRC", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.searchRCRequestBody Body;
        
        public searchRCRequest() {
        }
        
        public searchRCRequest(ABC_Shipment_Client.ShippingService.searchRCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchRCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public searchRCRequestBody() {
        }
        
        public searchRCRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchRCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchRCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.searchRCResponseBody Body;
        
        public searchRCResponse() {
        }
        
        public searchRCResponse(ABC_Shipment_Client.ShippingService.searchRCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchRCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABC_Shipment_Client.ShippingService.RetailCenter searchRCResult;
        
        public searchRCResponseBody() {
        }
        
        public searchRCResponseBody(ABC_Shipment_Client.ShippingService.RetailCenter searchRCResult) {
            this.searchRCResult = searchRCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertShipItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertShipItem", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.insertShipItemRequestBody Body;
        
        public insertShipItemRequest() {
        }
        
        public insertShipItemRequest(ABC_Shipment_Client.ShippingService.insertShipItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertShipItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int siid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float wei;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float dim;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ins;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float amnt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dest;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime deli;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int rid;
        
        public insertShipItemRequestBody() {
        }
        
        public insertShipItemRequestBody(int siid, float wei, float dim, string ins, float amnt, string dest, System.DateTime deli, int rid) {
            this.siid = siid;
            this.wei = wei;
            this.dim = dim;
            this.ins = ins;
            this.amnt = amnt;
            this.dest = dest;
            this.deli = deli;
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertShipItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertShipItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABC_Shipment_Client.ShippingService.insertShipItemResponseBody Body;
        
        public insertShipItemResponse() {
        }
        
        public insertShipItemResponse(ABC_Shipment_Client.ShippingService.insertShipItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertShipItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertShipItemResult;
        
        public insertShipItemResponseBody() {
        }
        
        public insertShipItemResponseBody(bool insertShipItemResult) {
            this.insertShipItemResult = insertShipItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ABC_ShippingServiceSoapChannel : ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ABC_ShippingServiceSoapClient : System.ServiceModel.ClientBase<ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap>, ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap {
        
        public ABC_ShippingServiceSoapClient() {
        }
        
        public ABC_ShippingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ABC_ShippingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABC_ShippingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ABC_ShippingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABC_Shipment_Client.ShippingService.insertRCResponse ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.insertRC(ABC_Shipment_Client.ShippingService.insertRCRequest request) {
            return base.Channel.insertRC(request);
        }
        
        public bool insertRC(int id, string type, string address) {
            ABC_Shipment_Client.ShippingService.insertRCRequest inValue = new ABC_Shipment_Client.ShippingService.insertRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.insertRCRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            inValue.Body.address = address;
            ABC_Shipment_Client.ShippingService.insertRCResponse retVal = ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).insertRC(inValue);
            return retVal.Body.insertRCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertRCResponse> ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.insertRCAsync(ABC_Shipment_Client.ShippingService.insertRCRequest request) {
            return base.Channel.insertRCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertRCResponse> insertRCAsync(int id, string type, string address) {
            ABC_Shipment_Client.ShippingService.insertRCRequest inValue = new ABC_Shipment_Client.ShippingService.insertRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.insertRCRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            inValue.Body.address = address;
            return ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).insertRCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABC_Shipment_Client.ShippingService.updateRCResponse ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.updateRC(ABC_Shipment_Client.ShippingService.updateRCRequest request) {
            return base.Channel.updateRC(request);
        }
        
        public bool updateRC(int id, string type, string address) {
            ABC_Shipment_Client.ShippingService.updateRCRequest inValue = new ABC_Shipment_Client.ShippingService.updateRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.updateRCRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            inValue.Body.address = address;
            ABC_Shipment_Client.ShippingService.updateRCResponse retVal = ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).updateRC(inValue);
            return retVal.Body.updateRCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.updateRCResponse> ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.updateRCAsync(ABC_Shipment_Client.ShippingService.updateRCRequest request) {
            return base.Channel.updateRCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.updateRCResponse> updateRCAsync(int id, string type, string address) {
            ABC_Shipment_Client.ShippingService.updateRCRequest inValue = new ABC_Shipment_Client.ShippingService.updateRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.updateRCRequestBody();
            inValue.Body.id = id;
            inValue.Body.type = type;
            inValue.Body.address = address;
            return ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).updateRCAsync(inValue);
        }
        
        public bool deletetRC(int id) {
            return base.Channel.deletetRC(id);
        }
        
        public System.Threading.Tasks.Task<bool> deletetRCAsync(int id) {
            return base.Channel.deletetRCAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABC_Shipment_Client.ShippingService.searchRCResponse ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.searchRC(ABC_Shipment_Client.ShippingService.searchRCRequest request) {
            return base.Channel.searchRC(request);
        }
        
        public ABC_Shipment_Client.ShippingService.RetailCenter searchRC(int id) {
            ABC_Shipment_Client.ShippingService.searchRCRequest inValue = new ABC_Shipment_Client.ShippingService.searchRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.searchRCRequestBody();
            inValue.Body.id = id;
            ABC_Shipment_Client.ShippingService.searchRCResponse retVal = ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).searchRC(inValue);
            return retVal.Body.searchRCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.searchRCResponse> ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.searchRCAsync(ABC_Shipment_Client.ShippingService.searchRCRequest request) {
            return base.Channel.searchRCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.searchRCResponse> searchRCAsync(int id) {
            ABC_Shipment_Client.ShippingService.searchRCRequest inValue = new ABC_Shipment_Client.ShippingService.searchRCRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.searchRCRequestBody();
            inValue.Body.id = id;
            return ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).searchRCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABC_Shipment_Client.ShippingService.insertShipItemResponse ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.insertShipItem(ABC_Shipment_Client.ShippingService.insertShipItemRequest request) {
            return base.Channel.insertShipItem(request);
        }
        
        public bool insertShipItem(int siid, float wei, float dim, string ins, float amnt, string dest, System.DateTime deli, int rid) {
            ABC_Shipment_Client.ShippingService.insertShipItemRequest inValue = new ABC_Shipment_Client.ShippingService.insertShipItemRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.insertShipItemRequestBody();
            inValue.Body.siid = siid;
            inValue.Body.wei = wei;
            inValue.Body.dim = dim;
            inValue.Body.ins = ins;
            inValue.Body.amnt = amnt;
            inValue.Body.dest = dest;
            inValue.Body.deli = deli;
            inValue.Body.rid = rid;
            ABC_Shipment_Client.ShippingService.insertShipItemResponse retVal = ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).insertShipItem(inValue);
            return retVal.Body.insertShipItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertShipItemResponse> ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap.insertShipItemAsync(ABC_Shipment_Client.ShippingService.insertShipItemRequest request) {
            return base.Channel.insertShipItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABC_Shipment_Client.ShippingService.insertShipItemResponse> insertShipItemAsync(int siid, float wei, float dim, string ins, float amnt, string dest, System.DateTime deli, int rid) {
            ABC_Shipment_Client.ShippingService.insertShipItemRequest inValue = new ABC_Shipment_Client.ShippingService.insertShipItemRequest();
            inValue.Body = new ABC_Shipment_Client.ShippingService.insertShipItemRequestBody();
            inValue.Body.siid = siid;
            inValue.Body.wei = wei;
            inValue.Body.dim = dim;
            inValue.Body.ins = ins;
            inValue.Body.amnt = amnt;
            inValue.Body.dest = dest;
            inValue.Body.deli = deli;
            inValue.Body.rid = rid;
            return ((ABC_Shipment_Client.ShippingService.ABC_ShippingServiceSoap)(this)).insertShipItemAsync(inValue);
        }
        
        public bool deleteShipItem(int id) {
            return base.Channel.deleteShipItem(id);
        }
        
        public System.Threading.Tasks.Task<bool> deleteShipItemAsync(int id) {
            return base.Channel.deleteShipItemAsync(id);
        }
    }
}
